"""Ephemeral SQL Execution Sandbox using SQLAlchemy.

Evaluates semantic correctness by executing LLM-generated SQL in isolation and
comparing output against Ground Truth. Classifies results into exactly 4 states:
SUCCESS, FAILED, EMPTY, NONE.
"""

import logging
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError

from ..core.sql_utils import is_readonly_select

logger = logging.getLogger(__name__)


class EphemeralSandbox:
    """An isolated sandbox for executing untrusted LLM-generated SQL code.

    Evaluates semantic correctness by directly comparing outputs to Ground Truth
    executed queries. Utilizes SQLAlchemy to support universal database connection
    URIs. Classifies execution into exactly 4 states: SUCCESS, FAILED, EMPTY, NONE.
    """

    def execute_and_compare(
        self, predicted_sql: str, ground_truth_sql: str, db_uri: str
    ) -> str:
        """Executes the predicted query and evaluates results into exactly 4 states.

        Args:
            predicted_sql (str): SQL generated by the model.
            ground_truth_sql (str): Expected correct SQL query.
            db_uri (str): SQLAlchemy compatible database URI.

        Returns:
            str: One of the 4 states:
                 - ``'SUCCESS'``
                 - ``'FAILED: [traceback/details]'``
                 - ``'EMPTY: Data format inconsistency or overly strict filter...'``
                 - ``'NONE: Logical error or incorrect column selection...'``
        """
        if not is_readonly_select(predicted_sql):
            return "FAILED: Predicted SQL is empty or not a SELECT statement."

        try:
            engine = create_engine(db_uri)

            with engine.connect() as conn:
                # 1. Execute Ground Truth securely
                try:
                    gt_result = conn.execute(text(ground_truth_sql))
                    gt_columns = list(gt_result.keys())
                    gt_rows_raw = gt_result.fetchall()
                    gt_rows = set(gt_rows_raw)
                except SQLAlchemyError as gt_err:
                    return f"FAILED: Ground Truth Execution Error: {gt_err}"

                # 2. Execute Prediction securely
                try:
                    pred_result = conn.execute(text(predicted_sql))
                    pred_columns = list(pred_result.keys())
                    pred_rows_raw = pred_result.fetchall()
                    pred_rows = set(pred_rows_raw)
                except SQLAlchemyError as pred_err:
                    return (
                        f"FAILED: {type(pred_err).__name__}: {pred_err} "
                        f"| OffendingSQL: {predicted_sql}"
                    )

            # 3. Classify into 4 SOTA States
            if gt_rows == pred_rows:
                return "SUCCESS"

            # EMPTY: predicted returns 0 rows but ground truth has rows
            if len(pred_rows_raw) == 0 and len(gt_rows_raw) > 0:
                return (
                    "EMPTY: Data format inconsistency or overly strict filter. "
                    "Consider using LIKE instead of = for string fields, and verify "
                    f"filter values. OffendingSQL: {predicted_sql}"
                )

            # NONE: mismatch, wrong column selection, or all-NULL result
            all_nulls = len(pred_rows_raw) > 0 and all(
                val is None for row in pred_rows_raw for val in row
            )
            null_hint = " (Result contains only NULL values)" if all_nulls else ""

            missing = list(gt_rows - pred_rows)[:5]
            extra = list(pred_rows - gt_rows)[:5]

            return (
                f"NONE: Logical error or incorrect column selection. "
                f"Do NOT just add IS NOT NULL.{null_hint} "
                f"expected_columns={gt_columns}, predicted_columns={pred_columns}, "
                f"expected_count={len(gt_rows_raw)}, predicted_count={len(pred_rows_raw)}, "
                f"missing_expected_sample={missing}, extra_predicted_sample={extra}. "
                f"OffendingSQL: {predicted_sql}"
            )

        except Exception as e:
            logger.error(
                "[EphemeralSandbox] Unexpected sandbox failure for URI %s: %s",
                db_uri,
                e,
            )
            return f"FAILED: Unexpected crash: {e}"
